#pragma once

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX

#include <windows.h>

#include "native_api.h"
#include "third_party/safetyhook.hpp"

#include <algorithm>
#include <array>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <mutex>
#include <shared_mutex>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace gbfr::native
{
struct ResolvedGameLayout
{
   uintptr_t skill_apply_loop_limit_immediate_rva = 0;
   uintptr_t skill_apply_getter_return_rva = 0;
   uintptr_t skill_category_loop_limit_immediate_rva = 0;
   uintptr_t skill_fetch_path_rva = 0;
   uintptr_t skill_fetch_call_path_rva = 0;
   uintptr_t skill_category_getter_return_rva = 0;
   uintptr_t get_gem_data_by_index_rva = 0;
   uintptr_t status_rebuild_rva = 0;
   uintptr_t status_notifier_rva = 0;
   uintptr_t system_data_global_rva = 0;
   uintptr_t status_manager_global_rva = 0;
   uintptr_t ui_manager_global_rva = 0;
   uintptr_t ui_state_source_global_rva = 0;
   uintptr_t ui_selected_character_hash_offset = 0;
   uintptr_t ui_mode_offset = 0;
   uintptr_t ui_state_source_mode_offset = 0;
   uintptr_t status_map_sentinel_offset = 0;
   uintptr_t status_map_buckets_offset = 0;
   uintptr_t status_map_mask_offset = 0;
   uintptr_t status_character_hash_offset = 0;
   uintptr_t status_context_mode_offset = 0;
   uint8_t skill_apply_original_limit = 0;
   uint8_t skill_category_original_limit = 0;
};

inline constexpr int kNativeInternalSlotCount = 13;
// slots 0/1/2 of every character template are the mod-injected exclusives
// (T1/T2/war spirit, one factor per slot); player configuration only fills
// the slots after these. Total virtual slots =
// kBuiltinExclusiveSlotCount + config count.
inline constexpr int kBuiltinExclusiveSlotCount = 3;
inline constexpr int kVirtualSlotCapacity = 24;
// The restriction table (which character wears which exclusive gem) is compiled in:
// src/exclusive_table.inc, generated by docs\tool-gen-loadout.ps1 from gem.json's
// "character" rows — the generator asserts those to be 87 entries, so there is no
// runtime data file to read and nothing left to fail closed on at startup.
inline constexpr uint32_t kUnwornCharacterHash = 0x887AE0B0;
inline constexpr uint32_t kGranCharacterHash = 0x2A26B1B2;
inline constexpr uint32_t kDjeetaCharacterHash = 0xA4ACBA76;

// Template (synthesized) sigil slots use a slot-id range that can never
// collide with real inventory slot ids (0 .. 5099).
inline constexpr uint32_t kTemplateSlotIdBase = 0xFE000000u;

inline constexpr bool IsTemplateSlotId(uint32_t slot_id) noexcept
{
   return slot_id >= kTemplateSlotIdBase;
}

inline constexpr uint32_t MakeTemplateSlotId(int virtual_slot) noexcept
{
   return kTemplateSlotIdBase + static_cast<uint32_t>(virtual_slot);
}

struct TemplateGemSlot
{
   uint32_t gem_id = 0; // real gem hash for the gem-master lookup; 0 = empty slot
   uint32_t skill1 = 0;
   int32_t skill1_level = 0;
   // Single-skill slots must use kUnwornCharacterHash (0x887AE0B0): 0 makes the
   // game render an extra empty Lv1 entry in the full-sigil list.
   uint32_t skill2 = 0;
   int32_t skill2_level = 0;
   int32_t sigil_level = 0; // displayed sigil level (V+ = 15)
};

// Layout contract with GBFR20_TemplateSlot (native_api.h): same field order
// and packing; the ABI path only ever reads through a reinterpret_cast.
static_assert(sizeof(TemplateGemSlot) == sizeof(GBFR20_TemplateSlot));
static_assert(offsetof(TemplateGemSlot, gem_id) == offsetof(GBFR20_TemplateSlot, gem_id));
static_assert(offsetof(TemplateGemSlot, skill1) == offsetof(GBFR20_TemplateSlot, skill1));

struct CharacterTemplate
{
   uint32_t character_hash = 0;
   std::array<TemplateGemSlot, kVirtualSlotCapacity> slots{};
};

// Runtime template table: initialized from the built-in loadout and replaced
// by GBFR20_ApplyLoadout at runtime. Readers copy values under the shared
// mutex (same pattern as GetSelection) so detour paths stay lock-safe.
inline constexpr size_t kRuntimeTemplateCapacity = 32;
extern std::shared_mutex g_template_mutex;
extern std::array<CharacterTemplate, kRuntimeTemplateCapacity> g_runtime_templates;
extern std::atomic<int32_t> g_virtual_slot_count;

inline constexpr bool IsCaptainCharacterHash(uint32_t character_hash) noexcept
{
   return character_hash == kGranCharacterHash || character_hash == kDjeetaCharacterHash;
}

inline constexpr bool IsCharacterCompatible(
   uint32_t required_character_hash,
   uint32_t character_hash) noexcept
{
   return required_character_hash == 0 ||
      required_character_hash == character_hash ||
      (IsCaptainCharacterHash(required_character_hash) &&
       IsCaptainCharacterHash(character_hash));
}

static_assert(IsCharacterCompatible(kGranCharacterHash, kDjeetaCharacterHash));
static_assert(IsCharacterCompatible(kDjeetaCharacterHash, kGranCharacterHash));
static_assert(!IsCharacterCompatible(kGranCharacterHash, 0x18E2F9F9));
static_assert(!IsCharacterCompatible(0x18E2F9F9, kDjeetaCharacterHash));

// 布局预检字节表住在 layout_resolver.cpp 的匿名命名空间里：只有那一个翻译单元用它们，
// 放进共享内部头等于把实现细节当成模块接口发布。

using GemData = GBFR20_GemData;
static_assert(sizeof(GemData) == 0x24);

struct StatusIdentity
{
   uint32_t character_hash = 0;
   int32_t context_mode = -1;
};

// 上下文模式只有三个取值。这条判断在好几条"读状态身份"的路径上各要一次，所以边界只写在这里。
constexpr bool IsValidContextMode(int32_t context_mode)
{
   return context_mode >= 0 && context_mode <= 2;
}

struct AuthorizedStatus
{
   uintptr_t status = 0;
   uint32_t character_hash = 0;
   int32_t context_mode = -1;
   uint64_t generation = 0;
   std::array<uint32_t, kVirtualSlotCapacity> slots{};
};

struct NaturalContributionFrame
{
   uintptr_t status = 0;
   StatusIdentity identity{};
   std::array<uint32_t, kVirtualSlotCapacity> slots{};
   uint32_t expected = 0;
   uint32_t injected = 0;
   int next_slot = kNativeInternalSlotCount;
   bool active = false;
};

enum EditSessionState : int32_t
{
   EditSessionUnknownLocked = 0,
   EditSessionEquipment = 1,
   EditSessionMissionLocked = 2,
   EditSessionFreeTraining = 3,
};

enum ApplyResult : int
{
   ApplyResultNone = 0,
   ApplyResultAppliedDuringNativeRebuild = 2,
   ApplyResultSavedNoStatus = -1,
   ApplyResultVirtualCopyFailed = -2,
   ApplyResultStatusLookupFailed = -4,
   ApplyResultNativeRebuildFailed = -5,
   ApplyResultNativeSkillLoopMissing = -6,
   ApplyResultNotifierFailed = -7,
};

struct ActiveCallGuard
{
   explicit ActiveCallGuard(std::atomic_uint32_t& value) : counter(value)
   {
      counter.fetch_add(1, std::memory_order_acq_rel);
   }
   ~ActiveCallGuard()
   {
      counter.fetch_sub(1, std::memory_order_acq_rel);
   }
   std::atomic_uint32_t& counter;
};

template <size_t Size>
bool MatchesBytes(uintptr_t address, const std::array<uint8_t, Size>& expected) noexcept
{
   __try
   {
      return std::memcmp(reinterpret_cast<const void*>(address), expected.data(), Size) == 0;
   }
   __except (EXCEPTION_EXECUTE_HANDLER)
   {
      return false;
   }
}

extern uintptr_t g_image_base;
extern std::once_flag g_initialize_once;
extern std::atomic_bool g_hooks_ready;
extern std::atomic_bool g_layout_ready;
extern ResolvedGameLayout g_game_layout;
extern std::atomic_bool g_shutting_down;
extern std::atomic_bool g_shutdown_complete;
extern std::atomic<GBFR20_LogCallback> g_log_callback;
extern std::mutex g_message_mutex;
extern std::string g_runtime_message;

extern SafetyHookInline g_get_gem_hook;
extern SafetyHookMid g_skill_fetch_hook;

extern std::shared_mutex g_selection_mutex;
extern std::unordered_map<uint32_t, std::array<uint32_t, kVirtualSlotCapacity>> g_character_selections;
extern std::shared_mutex g_authorization_mutex;
extern std::unordered_map<uintptr_t, AuthorizedStatus> g_authorized_statuses;

extern std::atomic_int32_t g_edit_session_state;
extern std::atomic_uint64_t g_lifecycle_rebind_signature;
// 同一状态没到位时的下一次补排时间点（GetTickCount64 口径）。见 skill_hooks.cpp 的
// ScheduleSelectedStatusRebind：没到位就补排、到位即停，这个值只是节流。
extern std::atomic_uint64_t g_lifecycle_rebind_not_before_ms;
// 正在等副本的签名：排了重建、但游戏那份"装备/测试"副本还没真的复制出来。只有复制成功
// （skill 循环跑完且全部复制）才清回 0。授权匹配**不算**到位——装备页看的是副本。
extern std::atomic_uint64_t g_rebind_pending_signature;

extern std::atomic_bool g_pending_refresh;
extern std::atomic<uint32_t> g_pending_character_hash;
extern std::atomic_uint32_t g_pending_injected_count;
extern std::atomic_uint32_t g_next_apply_generation;
extern std::atomic_uint64_t g_queued_apply_request;
extern std::atomic_uint64_t g_apply_retry_not_before_ms;
extern std::atomic_bool g_apply_in_flight;
extern std::atomic_uint64_t g_active_apply_generation;
extern std::atomic_uint64_t g_claimed_apply_generation;
extern std::atomic_uint32_t g_active_apply_thread_id;
extern std::atomic_uint64_t g_active_apply_status;
extern std::atomic_bool g_native_apply_call_active;
extern std::array<std::atomic_uint32_t, kVirtualSlotCapacity> g_active_apply_slots;
extern std::atomic_uint32_t g_active_apply_expected_count;
extern std::atomic_uint64_t g_last_apply_generation;
extern std::atomic_uint32_t g_last_apply_character_hash;
extern std::atomic_uint32_t g_last_apply_expected_count;
extern std::atomic_uint32_t g_last_apply_injected_count;
extern std::atomic_int g_apply_result;
extern std::atomic_uint32_t g_active_getter_calls;
extern std::atomic_uint32_t g_active_mid_calls;
extern thread_local uint64_t g_tls_apply_generation;
extern thread_local NaturalContributionFrame g_tls_natural_contribution;

int GetVirtualSlotCount() noexcept;
int GetExpandedInternalSlotCount() noexcept;
bool IsInWritableImageSection(uintptr_t rva, size_t size) noexcept;
// 游戏自己的代码段（PE 视图的唯一持有者仍是 layout_resolver.cpp：先按名字找 `.text`，
// 找不到才取最大的可执行段）。锚点扫描要的三个量就是它 + 映像大小 + PE 指纹。
struct CodeSectionView
{
   uintptr_t rva = 0;
   size_t size = 0;
   uintptr_t image_size = 0;
   uint32_t timestamp = 0;
};

bool TryGetCodeSection(CodeSectionView& view) noexcept;
void Log(const std::string& message);
// Phases are timed with GetTickCount64 at the call site and log once on
// completion (with elapsed time); failures are still reported explicitly, so a
// stuck startup is identifiable by the last completed phase.
void CompleteStartupPhase(std::string_view phase, uint64_t started_at_ms, bool succeeded);
void SetRuntimeMessage(std::string message);

bool SafeReadPointer(uintptr_t address, uintptr_t& value) noexcept;
bool SafeReadUint64(uintptr_t address, uint64_t& value) noexcept;
// 游戏内存的范围闸：整段（可跨多个区域）都必须已提交、非 PAGE_GUARD、且保护位满足要求。
// 游戏内存的读取与范围判断都归 safe_game_access.cpp（见 §6 的边界），别在别处再写一份。
// 这两种掩码就是仅有的两种用法：读一个指针字段 / 写整张表。
inline constexpr uint32_t kReadableProtect =
   PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY |
   PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
inline constexpr uint32_t kWritableProtect =
   PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
bool IsGameRange(uintptr_t address, size_t size, uint32_t required_protect) noexcept;
bool SafeReadUiSelectedCharacterHash(uint32_t& character_hash) noexcept;
void SafeReadUiModes(int32_t& ui_mode, int32_t& source_mode) noexcept;
void UpdateEditSessionState() noexcept;
bool SafeReadStatusIdentity(uintptr_t status, StatusIdentity& identity) noexcept;
bool SafeResolveStatusByMapKey(uintptr_t manager, uint32_t map_key, uintptr_t& status) noexcept;
bool SafeResolveCharacterStatus(uint32_t character_hash, uintptr_t& manager, uintptr_t& status) noexcept;
bool SafeResolveSelectedCharacterStatus(uint32_t character_hash, uintptr_t& manager, uintptr_t& status, StatusIdentity& identity) noexcept;
void CommitAuthorizedStatus(uintptr_t status, const StatusIdentity& identity, uint64_t generation, const std::array<uint32_t, kVirtualSlotCapacity>& slots);
bool TryGetAuthorizedSelection(uintptr_t status, const StatusIdentity& identity, std::array<uint32_t, kVirtualSlotCapacity>& slots);
bool HasMatchingAuthorizedSelection(uintptr_t status, const StatusIdentity& identity, const std::array<uint32_t, kVirtualSlotCapacity>& slots);
bool TryGetAuthorizedContext1Status(uint32_t character_hash, AuthorizedStatus& authorization);
void EraseAuthorizedStatus(uintptr_t status);
void ValidateAuthorizedStatuses();
bool SafeCopyToOutput(const GemData& source, void* destination) noexcept;
bool SafeInvokeStatusRebuild(uintptr_t status, uint32_t character_hash, StatusIdentity& restored_identity, bool preserve_context) noexcept;
bool SafeNotifyStatusDirty(uintptr_t manager, uint32_t character_hash, uint32_t dirty_mask) noexcept;
bool ReadByte(uintptr_t address, uint8_t& value) noexcept;
bool WriteByte(uintptr_t address, uint8_t value);

std::array<uint32_t, kVirtualSlotCapacity> GetSelection(uint32_t character_hash);
// Bumps the shared apply generation; never returns 0 (0 means "no generation"
// in the detour's pending-apply checks).
uint32_t NextApplyGeneration();
void RequestHotApply(uint32_t character_hash);
void ProcessPendingHotApply();

bool TryGetRuntimeSlot(uint32_t character_hash, int virtual_slot, TemplateGemSlot& out) noexcept;
void InitializeRuntimeTemplates();
bool ApplyLoadout(
   const TemplateGemSlot* slots, int32_t slot_count,
   const GBFR20_ExclusiveOverride* overrides, int32_t override_count) noexcept;
void InstallDefaultTemplateSelections();
// 模板表变过之后必须做的事，只有这一个入口（发布选择 + 排一次状态重建）。
void PublishTemplateSelections() noexcept;
bool TryCopyTemplateGem(uint32_t character_hash, uint32_t selected_slot_id, void* output) noexcept;
bool ApplySkillLoopLimits(int32_t virtual_slot_count) noexcept;

void ScheduleSelectedStatusRebind();
bool ResolveGameLayout();
bool RevalidateGameLayout();
void ResetGameLayout() noexcept;
void ShutdownHooks();
bool InstallHooks();
void Initialize();
void EnsureInitialized();
// 从语义锚点解析游戏发布 skill_status 表的那个固定槽，并把**槽首** RVA 缓存在
// src/table_slot.cpp 里：WriteSkillStatusTable 每次调用都从它取地址（缓冲区指针字段在槽首 +8，
// 现算，不另存一份）。解析失败只记日志，不影响其余任何初始化——热应用没有第二条路，只会拒写。
void ResolveTableSlot();
// GBFR20_WriteSkillStatusTable 的实现：校验后把整表按行差异写进游戏那份活表。
// 返回 >= 0 是改写的行数；< 0 是 native_api.h 里的拒绝码（写之前的每一道闸都不动内存）。
int32_t WriteSkillStatusTable(const uint8_t* table, size_t length) noexcept;
void ConsumeApplyResult();
}
