export const MAX_SLOTS = 12 // fixed rows shown in the editor
/** Fallback sigil/trait level when no cap is known (mirrors C# DefaultLevel). */
export const DEFAULT_LEVEL = 15
/** Menu hotkey fallback when tool-hotkey.txt is unavailable (F1). */
export const DEFAULT_HIDE_KEY = 0x70

export interface Slot {
  mainHash: string
  mainLevel: number
  secHash: string
  secLevel: number
  enabled: boolean
}

/** One entry of a saved loadout.json slot item list (the file shape).
 * level stays optional: a hand-edited file may omit it (DEFAULT_LEVEL).
 * Older builds also wrote zh/en here; the mod never read them and nothing
 * writes them anymore — names are not part of the data. */
export interface SavedItem {
  gem?: string
  hash?: string
  level?: number
}

export interface Sigil {
  hash: string // gem hash (= item identity; skill entries use the trait hash)
  skill1: string // primary trait hash — the main picker's group key
  player: string
  onlyone?: string // gem.CanOnlyHoldOne: "1" = 唯一持有
  mix?: string // gem.CanGemMix: "0" ordinary (free combination), "1" locked
  cap?: number // trait level cap (row data, feeds the trait dictionary only)
  lot?: string[] // pool versions: legal secondary trait hashes (empty = no pool)
  skill2?: string // fixed-second versions: the fixed secondary trait hash
}

export interface Trait {
  hash: string
  /** 命名这个词条的那一行物品的 hash：显示名按它去 gem.lang.json 里取。 */
  gem: string
  cap: number
}

/** One row of gem.chara.json (generated by tool-gen-loadout.ps1):
 * 每个角色三个专属槽，按槽位顺序存 [因子 hash, 技能 hash] 对。 */
export interface Exclusive {
  hash: string // 角色 hash：只在迁移旧配置时当键用（loadout.json 的键是 PL 码）
  player: string // PL 码，也是 chara.lang.json 的键
  gems: [string, string][] // [因子 hash, 技能 hash] ×3
}

/** 一条专属记录的三个槽：写入配置的键 + 屏幕上的名字。
 *
 * 元组按位置读，0 = T1、1 = T2、2 = 战气。两个 hash 各管一头，不能对调：
 * loadout.json 的状态键是**技能** hash（`[1]`），而名字表 gem.lang.json 以
 * **因子物品** hash（`[0]`）为键——取错一个下标，整页标签就退化成裸 hash。
 * 所以这个读法只留在这里，别在组件里再解构一次。 */
export function exclusiveSlots(
  row: Exclusive,
  names: Record<string, string>
): { traitHash: string; label: string }[] {
  return row.gems.map(([gem, skill]) => ({ traitHash: skill, label: names[gem] ?? gem }))
}

/** The trust boundary for gem.chara.json: 形状不完整的记录整条丢掉，与 mod 侧
 * LoadExclusiveTable 同一条规则。非数组直接抛，交给调用方的错误提示。 */
export function parseExclusiveTable(raw: unknown): Exclusive[] {
  if (!Array.isArray(raw)) throw new Error("gem.chara.json is not an array")
  return raw.filter(
    (row): row is Exclusive =>
      typeof row?.hash === "string" &&
      typeof row?.player === "string" &&
      Array.isArray(row?.gems) &&
      row.gems.length === 3 &&
      row.gems.every(
        (g: unknown) =>
          Array.isArray(g) && g.length === 2 && g.every((h) => typeof h === "string")
      )
  )
}

/** Exclusive overlay written to loadout.json: player code -> trait hash -> enabled. */
export type ExclusiveState = Record<string, Record<string, boolean>>

/** Keys that must never be written into the plain exclusive state object. */
const BLOCKED_KEYS = new Set(["__proto__", "constructor", "prototype"])

/** Sanitize a loaded "exclusive" object: drop prototype keys and non-boolean
 * values so a hand-written file cannot pollute the editor state. */
export function sanitizeExclusiveState(raw: unknown): ExclusiveState | undefined {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return undefined
  const out: ExclusiveState = {}
  for (const [player, value] of Object.entries(raw as Record<string, unknown>)) {
    if (BLOCKED_KEYS.has(player)) continue
    if (!value || typeof value !== "object" || Array.isArray(value)) continue
    const inner: Record<string, boolean> = {}
    for (const [trait, enabled] of Object.entries(value as Record<string, unknown>)) {
      if (BLOCKED_KEYS.has(trait)) continue
      if (typeof enabled === "boolean") inner[trait] = enabled
    }
    out[player] = inner
  }
  return Object.keys(out).length > 0 ? out : undefined
}

const emptySlot = (): Slot => ({ mainHash: "", mainLevel: 0, secHash: "", secLevel: 0, enabled: true })

/** Normalize a saved config (new array format) into Slot[].
 *
 * 存档里存的是 gem hash，而下拉的值是**组键**（该行所属的词条 hash，`skill1`），
 * 所以这里把前者翻成后者；表里没有的 gem 保留原值（下一次保存会被丢弃，
 * 编辑里也显示为空）。名字不参与：它按语言变，不能当身份。
 *
 * Levels are clamped to the cap the table knows about so an out-of-range
 * hand-edited value cannot make the mod reject the file. */
export function configToSlots(
  parsed: { slots?: unknown },
  sigils: Sigil[],
  traits: Trait[] = []
): Slot[] {
  const capOfTrait = new Map(traits.map((tr) => [tr.hash, tr.cap]))
  const capOfGem = new Map<string, number | undefined>(
    sigils.map((s) => [s.hash, capOfTrait.get(s.skill1)])
  )
  const fromCfg = slotsFromConfig(parsed?.slots, capOfGem, capOfTrait)
  const mainKeyOfGem = new Map(sigils.map((s) => [s.hash, s.skill1 || s.hash]))
  for (const s of fromCfg) {
    if (mainKeyOfGem.has(s.mainHash)) s.mainHash = mainKeyOfGem.get(s.mainHash) as string
  }
  return fromCfg
}

/** Pad the editor to at least MAX_SLOTS rows so the user just fills them in.
 * Extra rows from an over-long saved config pass through: the Go/C# validators
 * reject them instead of silently truncating (data loss on next autosave). */
export function pad12(slots: Slot[]): Slot[] {
  const out = [...slots]
  while (out.length < MAX_SLOTS) out.push(emptySlot())
  return out
}

/** Clamp a stored level to the table cap when one is known. */
const clampLevel = (level: number, cap: number | undefined) =>
  cap === undefined ? level : Math.max(0, Math.min(level, cap))

/** The trust boundary for saved configs: untrusted JSON shape -> Slot[].
 * Every field is guarded, so a hand-edited or truncated loadout.json degrades
 * to empty slots instead of throwing. The two cap maps are required - the only
 * caller always has both. */
function slotsFromConfig(
  raw: unknown,
  capOfGem: Map<string, number | undefined>,
  capOfTrait: Map<string, number>
): Slot[] {
  const arr = Array.isArray(raw) ? raw : []
  return arr.map((slot) => {
    const s = (slot ?? {}) as {
      enabled?: boolean
      items?: SavedItem[]
    }
    const items = Array.isArray(s.items) ? s.items : []
    const main = items[0] ?? {}
    const sec = items[1]
    const mainHash = typeof main.gem === "string" ? main.gem : "" // items[0] has no "hash" variant (never written)
    const secHash = sec && typeof sec.hash === "string" ? sec.hash : ""
    const mainLevel = typeof main.level === "number" ? main.level : DEFAULT_LEVEL
    const secLevel = sec && typeof sec.level === "number" ? sec.level : DEFAULT_LEVEL
    return {
      mainHash,
      mainLevel: clampLevel(mainLevel, capOfGem.get(mainHash)),
      secHash,
      secLevel: clampLevel(secLevel, capOfTrait.get(secHash)),
      enabled: s.enabled !== false,
    }
  })
}
